### ISSUE TITLE
logo?

### ISSUE THREAD

**Issue by buzzdecafe** [HartfordJS/talks#15]
just tinkering with inkscape. here is a first pass.
![hjs](https://f.cloud.github.com/assets/716260/456922/1b02914a-b37e-11e2-9267-09efa23bb24e.png)

not completely happy with the shape of the "S". thoughts?

**Comment by CrossEye** [comment]
I think it's very clever and quite well done.  I agree about the S, but also think that with an S, the J needs a bit more of a bowl.  So any chance that a twenty-years dead organization can complain about trademark infringement?  :-)

**Comment by buzzdecafe** [comment]
"JS" adapted from here: https://github.com/voodootikigod/logo.js
whaletail from here: http://en.wikipedia.org/wiki/File:Hartford_Whalers_Logo-79-92.svg

**Comment by willklein** [comment]
There are two repos right now, one for talks and one for the site. This belongs under the issue already started under the hartfordjs.com repo.

Regarding the trademark, the Whalers were here until 1997. There is a lot of mixed information regarding who owns the trademark now, but _someone_ has the rights (NHL, Carolina Hurricanes, or City of Hartford). I don't know if they or anyone would care about the logo getting forked for a local user group.

**Comment by willklein** [comment]
I'm closing this issue. It's already open under the website repo:

https://github.com/HartfordJS/hartfordjs.com/issues/4
