### ISSUE TITLE
Node.js

### ISSUE THREAD

**Issue by willklein** [HartfordJS/talks#2]
Introduce Node.js. Demonstrate a simple web server/service.

Maybe start with something useful like Express.

Introduce NPM and explain how to add packages.

Joshua expressed interest in talking on this. Some of us worked on a Node Knockout app back in November, we could share that. There's also a local startup that uses a Node stack, I'd like to get them in to talk about their work. I expect we will have multiple presentations on this.

**Comment by jtenner** [comment]
<h1>Node.js Roundup Talk</h1>

I want to reach out and make node more accessible to people. In fact, the kind of stuff I want to talk about should be beginner oriented.

I can list a billion topics here, but I have collected a list of things that I think are easy to pick up here:
1. **What is Node?** (Definitely doing this one)
   - How to install (Linux, Mac, PC)
   - Common Uses
   - NPM tutorial
   - Getting Started
2. **Commander**
   - Creating a command line application
3. **NodeTDS** (Node to SQL Server)
4. **HTTP** (Web requests)
5. **FS** (file system)
6. **Using Coffeescript** (How to install it and run it, not how to code in coffeescript)

_**Please email me at [tenner.joshua@gmail.com](mailto:tenner.joshua@gmail.com)**_ with ideas about what you would like to learn about node.

I will have live examples on my laptop... hopefully.

**Comment by willklein** [comment]
This looks great. I'm not sure about fitting CoffeeScript in, that probably deserves its own presentation.

Another idea is to finish off with deployment options like Heroku, Nodejitsu, etc. Introducing one of those briefly is good for anyone that's unfamiliar.

**Comment by AutoSponge** [comment]
I would also like to hear a Node talk...

**Comment by willklein** [comment]
I see your note about how to install and run CoffeeScript. I see how that would be useful!

**Comment by jtenner** [comment]
Still working on the presentation. Will keep you guys posted.
